name: Bug report
description: Report a problem with KeyWave
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for helping improve KeyWave."
  - type: input
    id: device
    attributes:
      label: Device and Android version
      placeholder: "Pixel 6, Android 14"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: "Only if logging is enabled"
